### PR TITLE
Correction of "trade" command

### PR DESCRIPTION
**Pull request by syokkendesuyo**
Processing in the absence of arguments was missing.
・If it is only "/ trade", we can get help.
・Help made function

### CODE REVIEW

**Comment by syokkendesuyo** [comment]
I modified the "trade" command. Can you give me permission?

**Comment by BtoBastian** [comment]
Hello,
your pull request contains no changes? However, thank you for mentioning this bug. 👍

**Comment by syokkendesuyo** [comment]
hi BtoBastian.
https://help.github.com/articles/permission-levels-for-a-user-account-repository/

I have made a wrong request because some of the permissions to send a pull request are missing.
I'd like you to give me the necessary authority if possible.

**Comment by BtoBastian** [comment]
Hey,
You don't need any special permission to create a Pull Request. 
However, the bug is already fixed in the latest version (1.0.12): https://github.com/BtoBastian/SafeTrade/commit/f1473e89bcbe821253d255bad13062b5bb698faf
Thx for reporting!

**Pull request closed without merging**
